=== xqstrive/MilkC/milk_1_0.dtd
<!--
 This file is for Milk framework, https://github.com/xqstrive/Milk.
 You can use xml configure you project, but now the property is used.
 Author Wangqi xqstrive@gmail.com
 Created in 2017/2/15
 Last modified in 2017/2/15
-->

<!ELEMENT milk (static-path?, encoding?, initial-capacity?, load-factor?,app*)>

    <!ELEMENT static-path (#PCDATA)>

    <!ELEMENT encoding (#PCDATA)>

    <!ELEMENT initial-capacity (#PCDATA)>

    <!ELEMENT load-factor (#PCDATA)>

    <!ELEMENT app (app-name,urls)>

        <!ELEMENT app-name (#PCDATA)>

        <!ELEMENT urls (url+)>

            <!ELEMENT url (url-name,url-service?,url-template?)>

                <!ELEMENT url-name (#PCDATA)>

                <!ELEMENT url-service (#PCDATA)>

                <!ELEMENT url-template (#PCDATA)>

=== xqstrive/MilkC/src/main/webapp/WEB-INF/milk.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE milk SYSTEM "https://raw.githubusercontent.com/xqstrive/MilkC/master/milk_1_0.dtd">

<milk>
    <static-path></static-path>
    <encoding>UTF-8</encoding>
    <initial-capacity>16</initial-capacity>
    <load-factor>0.75f</load-factor>



    <app>
        <app-name>/</app-name>
        <urls>
            <url>
                <url-name>/</url-name>
                <url-service>app.ServiceHelloWorld</url-service>
                <url-template>\template\test1.html</url-template>
            </url>
            <url>
                <url-name>/index</url-name>
                <url-service></url-service>
                <url-template>\template\index.html</url-template>
            </url>
            <url>
                <url-name>/sign</url-name>
                <url-service></url-service>
                <url-template>\template\sign.html</url-template>
            </url>
        </urls>
    </app>

</milk>
